import Head from "next/head";
import Link from "next/link";

// REACT ICONS
import { BsArrowRightShort } from "react-icons/bs";

// Styled Components
import * as Style from "../styles/style";

// Componentes
import MenuBottom from "../components/MenuBottom";
import MenuTop from "../components/MenuTop";
import CardHome from "../components/CardsHome";
import ButtonSearch from "../components/ButtonSearch";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cozinha Prateada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuTop />

      <Style.Main>
        <section className="content">
          <div className="texto">
            <h1>Olá, Walyson</h1>
            <p>Vamos ver seu pedido!</p>
          </div>
          <ButtonSearch />
          <CardHome />
          <div className="texto2">
            <span>Populares</span>
            <span>
              <Link href="">
                <a>
                  <BsArrowRightShort color="#c8161d" size={30} />
                  Todos
                </a>
              </Link>
            </span>
          </div>
        </section>
      </Style.Main>

      <MenuBottom />
    </>
  );
}
